# アスキーコメントのみ許可
Style/AsciiComments:
  Enabled: false

# アスキーの変数名のみ許可
Naming/AsciiIdentifiers:
  Enabled: false

Metrics/LineLength:
  Max: 120


Style/Encoding:
  Enabled: true

# Style/TrailingCommaInLiteral:
#   EnforcedStyleForMultiline: comma
