# アスキーコメントのみ許可
AsciiComments:
  Enabled: false

# アスキーの変数名のみ許可
Naming/AsciiIdentifiers:
  Enabled: false

LineLength:
  Max: 120

Metrics/LineLength: 120

Style/Encoding:
  Enabled: true

# Style/TrailingCommaInLiteral:
#   EnforcedStyleForMultiline: comma
