language: objective-c
sudo: true
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
matrix:
  include:
    # - os: linux
    - os: osx

before_install:
  - echo ""
  # - brew update
  # - brew install python
  # - brew install ansible
  # - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"'
  # - rm -rf /usr/local/Homebrew
  # - rm -rf /usr/local/Caskroom
  # - rm -rf /usr/local/bin/brew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi

install:
  - sudo -H easy_install pip
  - sudo -H pip install ansible
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

  # Add ansible.cfg to pick up roles path.
  # - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

    # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  - ansible --version
  - ansible-galaxy install -r requirements.yml
  # - ansible-playbook --syntax-check ./localhost.yml -i hosts
  - ansible-playbook --syntax-check ./localhost.yml
  - "travis_wait 30 ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' localhost.yml"
  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' localhost.yml | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
