---
- hosts: localhost
  connection: local
  vars:
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.4.1
      rubies:
      - version: 2.4.1
  pre_tasks:
    - name: show environment
      debug: msg="USER={{ ansible_env.USER }} HOME={{ ansible_env.HOME }}\nPATH={{ ansible_env.PATH }}"
    - name: get python version
      command: python --version
      register: python_version
      check_mode: no
      changed_when: false
    - name: show python verion
      debug:
        msg: "{{ python_version }}"
  roles:
    - role: common
    - role: python
    - role: shell
    - role: scala
    - role: ruby
    # - role: js
    #   vars:
    #     nodebrew_install_user: pogin
    # - role: geerlingguy.nodejs
    #   become: true
    #   npm_config_unsafe_perm: true
    #   nodejs_npm_global_packages:
    #     - name: jslint
    #     - name: node-sass
    #     - name: purescript
    #     - name: pulp
    #     - name: bower
    # - role: geerlingguy.mysql
    #   become: yes
