---
- hosts: localhost
  connection: local
  vars:
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.4.1
      rubies:
      - version: 2.4.1
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/binary
      - railwaycat/emacsmacport
  pre_tasks:
    - debug: msg="USER={{ ansible_env.USER }} HOME={{ ansible_env.HOME }}"
    - name: show python version
      command: python --version
      changed_when: false
  roles:
    - role: common
    - role: python
    - role: scala
    - role: ruby
    # - role: js
    #   vars:
    #     nodebrew_install_user: pogin
    # - role: geerlingguy.nodejs
    #   become: true
    #   nodejs_npm_global_packages:
    #     - name: jslint
    #     - name: node-sass
    # - role: geerlingguy.mysql
    #   become: yes
