---
- hosts: localhost
  connection: local
  vars:
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.4.1
      rubies:
      - version: 2.4.1
  pre_tasks:
    - debug: msg="USER={{ ansible_env.USER }} HOME={{ ansible_env.HOME }}"
    - name: show python version
      shell: |
        python --version
      changed_when: false
  roles:
    - role: common
    - role: python
    - role: scala
    - role: ruby
