---
- name: dotfiles Playbook
  hosts: vagrants
  pre_tasks:
    - name: install dpendencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
        - python3-pip
        - build-essential
        # ruby dependencies
        - autoconf
        - bison
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm3
        - libgdbm-dev
        # mysql dependencies
        - libmysqlclient-dev
        - python3-dev
        - python3-pip
        - python3-mysqldb
        # ats2 dependency
        - libgmp3-dev
      when: ansible_distribution == 'Ubuntu'

    # https://github.com/geerlingguy/ansible-role-mysql/issues/42
    - block:
        - name: install mysql dependencies (pip)
          pip:
            name: "{{ item.name }}"
            state: "{{ item.state }}"
          with_items:
            - name: https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-1.1.6.tar.gz
              state: present
            # mysql dependencies
            - name: mysqlclient
              state: present
            - name: pip
              state: latest
        - shell: |
            python3 --version
            pip3 --version
          changed_when: false
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role: common
    # - role: python
    # - role: scala
    - role: ruby
      ruby_version: 2.4.1
    - role: geerlingguy.nodejs
      become: yes
      nodejs_npm_global_packages:
        - name: jslint
        - name: node-sass
    - role: geerlingguy.mysql
      become: yes
      mysql_databases:
        - name: example
          collation: utf8_general_ci
          encoding: utf8
          # replicate: 1
      mysql_packages:
        - mariadb-client
        - mariadb-server
        - python-mysqldb
      mysql_users:
        - name: pogin
          host: "%"
          password: mysqlpass00
          priv: "example_db.*:ALL"
