---
homebrew_cask_packages:
- { name: dropbox }
- { name: google-chrome }
- { name: kindle }
- { name: mactex }
- { name: mendeley-desktop }
- { name: pgadmin4 }
- { name: powershell }
- { name: skype }
- { name: vagrant }
- { name: virtualbox }
- { name: vlc }
