---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: macOS.yml
  when: ansible_os_family == 'Darwin'

- name: Upgrade pip
  become: true
  pip:
    name: "{{ item.name }}"
    extra_args: --upgrade
  with_items:
    - { name: pip }
    - { name: setuptools }
    - { name: wheel }

- name: Related to machine learning packages
  become: true
  pip:
    name: "{{ item.name }}"
    state: present
    extra_args: --user
  with_items: "{{ ml_packages }}"
  tags: install

- name: common packages
  pip:
    name: "{{ item.name }}"
    state: present
    extra_args: --user
  with_items: "{{ python_packages }}"
  tags: install

# - name: Install Mecab
#     debug: "Download Mecab"
#     - get_url:
#         url: https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
#         dest: /tmp
