---
- name: install dpendencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
    - { name: git } 
    - { name: python3-pip }
    - { name: build-essential }

- name: make directory
  file:
    path: "$HOME/.config/pip"
    state: directory

- name: copy pip.conf
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/python/pip.conf"
    dest: "$HOME/.config/pip/pip.conf"
    state: link
    force: yes
