- name: machine learning
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ml_packages }}"

- name: common package
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_packages }}"

- name: Install Python3 kernel
  shell: >-
    python3 -m IPython kernelspec install-self

