- name: machine learning
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ml_packages }}"

- name: common
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_packages }}"



