---
- block:
    - name: copy pip.conf
      file:
        src: "{{ ansible_env.PWD }}/python/pip.conf"
        dest: "$HOME/Library/Application Support/pip/pip.conf"
        state: link
        force: yes
      when: ansible_os_family == 'Darwin'
    - name: copy pip.conf
      file:
        src: "~/dotfiles/python/pip.conf"
        dest: "$HOME/.config/pip/pip.conf"
        state: link
        force: yes
      when: ansible_os_family == 'Ubuntu'
  rescue:
    - name: for travis-ci setting
      shell: "false"
      ignore_errors: yes
      when: "{{ ansible_env.USER }}  == 'travis'"
   
- name: upgrade pip
  become: true
  pip:
    name: pip
    state: latest

- name: Related to machine learning packages
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ml_packages }}"

- name: common packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_packages }}"

# - name: Install Mecab
#     debug: "Download Mecab"
#     - get_url:
#         url: https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
#         dest: /tmp

