---
- block:
    - name: copy pip.conf
      file:
        src: "{{ ansible_env.PWD }}/python/pip.conf"
        dest: "$HOME/Library/Application Support/pip/pip.conf"
        state: link
        force: yes
      when: ansible_os_family == 'Darwin' and ansible_env.USER  != 'travis'

    - name: copy pip.conf
      file:
        src: "{{ ansible_env.PWD }}/dotfiles/python/pip.conf"
        dest: "$HOME/.config/pip/pip.conf"
        state: link
        force: yes
      when: ansible_os_family == 'Ubuntu'

- name: Upgrade pip
  become: true
  pip:
    name: pip
    extra_args: --upgrade

- name: Related to machine learning packages
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ml_packages }}"

- name: common packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_packages }}"

# - name: Install Mecab
#     debug: "Download Mecab"
#     - get_url:
#         url: https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
#         dest: /tmp
