---
- name: upgrade pip
  pip:
    name: pip
    state: latest

- name: Related to machine learning packages
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ml_packages }}"

- name: common packages
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ python_packages }}"


