- name: machine learning
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - jupyter
    - scikit-learn
    - jedi
    - epc
    - flake8
    - pygments
    - ipython
    - requests


