---
- name: Download install shell
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /tmp
    mode: '0755'

- name: execute install shell
  ansible.builtin.shell:
    cmd: ./install_update_linux.sh
    chdir: /tmp
