version: '3'

services:
  ubuntu: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "dotfiles:/root/dotfiles"
    # image: ubuntu:22.04
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    command: /sbin/init

volumes:
  dotfiles:
    external: true
