---
# - include_role:
#     name: djyugg.nodebrew

# - name: Install nodebrew
#   roles:
#     role: djyugg.nodebrew
# name: Install nodebrew
- include_role:
    name: stephdewit.nvm
# - block:
#     - name: donwload nodebrew script
#       get_url:
#         url: https://git.io/nodebrew
#         dest: "$HOME/workspace/"
#         mode: 0755
#         force: yes
#     - name: Install nodebrew
#       command: perl nodebrew setup
#       args:
#         chdir: "$HOME/workspace/"
#       changed_when: false

# # https://truongtx.me/2015/11/02/ansible-install-and-work-with-nodejs-using-nvm
# - name: Install npm modules
#   npm:
#     name: "{{ item.name }}"
#     state: "{{ item.state }}"
#     # executable: "~/.nvm/versions/node/v{{ nvm_node_version }}/bin/npm"
#     global: yes
#   with_items: "{{ nodejs_npm_global_packages }}"
#   environment:
#     PATH: "/usr/local/bin:~/.nvm/versions/node/v{{ nvm_node_version }}/bin:{{ ansible_env.PATH }}"
#     PATH: "/usr/local/bin:~/.local/share/nvm/versions/node/v10.15.0/bin:{{ ansible_env.PATH }}"
