galaxy_info:
  author: pogin503
  description: pogin503
  # company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: MIT (GPLv2, CC-BY, etc)

  min_ansible_version: 2.0

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  # example:
  #   dependencies:
  #     - { role: mysql/client }
  #     - { role: lxc/redhat, when: "ansible_os_family == 'RedHat'" }
  #     - { role: lxc/debian, when: "ansible_os_family == 'Debian'" }
  #     - { role: common, some_parameter: 3 }
  #     - { role: apache, apache_port: 80 }
  #     - { role: postgres, dbname: blarg, other_parameter: 12 }
  #     - src: geerlingguy.docker
  #     - src: git+https://github.com/geerlingguy/ansible-role-composer.git
  #       version: 775396299f2da1f519f0d8885022ca2d6ee80ee8
  #       name: composer
