---
ml_packages:
  - jupyter
  - jupyter_contrib_nbextensions
  - scikit-learn
  - environment_kernels
  - numpy
  - matplotlib
  - bokeh
  - plotly

python_packages:
  - jedi
  - epc
  - flake8
  - pygments
  - requests
