- name: create iterm2 log directory
  become: true
  file: path=/var/log/iterm2 state=directory owner=root group=admin mode=0775
  when: ansible_os_family == 'Darwin'

- name: Set homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - railwaycat/emacsmacport
    - sanemat/font

- name: install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - fish
    - go
    - ansifilter
    - the_silver_searcher
    - ricty
    - editorconfig
    - jenkins
    - shellcheck
    - tmux
    - trash
    - tree
  tags: brew-install

- name: install packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - appcleaner
    - dropbox
    - eclipse-platform
    - google-chrome
    - google-chrome-canary
    - kindle
    - mendley-desktop
    - postico
    - powershell
    - vagrant
    - virtualbox
    - visual-studio-code
    - vlc
