---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: set dotfiles
  git: repo='https://github.com/pogin503/dot-files.git'
       dest={{ ansible_env.HOME }}/dotfiles
       version=master
       force=yes
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: exec setup.sh
  shell: "{{ ansible_env.HOME }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles/"
  changed_when: false

- import_tasks: macOS.yml
  when: ansible_os_family == 'Darwin'

- name: Create plantuml directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/plantuml/"
    state: directory
    mode: 0755

- name: Download PlantUML jar
  get_url:
    url: http://jaist.dl.sourceforge.net/project/plantuml/plantuml.jar
    dest: "{{ ansible_env.HOME }}/.local/share/plantuml/"
