---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: set dotfiles
  git: repo='https://github.com/pogin503/dot-files.git'
       dest={{ ansible_env.HOME }}/dotfiles
       version=master
       force=yes

- name: exec setup.sh
  script: "{{ ansible_env.HOME }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles/"
  register: ret
  changed_when: false

- import_tasks: macOS.yml
  when: ansible_os_family == 'Darwin'
