---
- name: install dpendencies (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python-pip
    - libtool-bin
  become: true
  when: ansible_distribution == 'Ubuntu'

# - include: ubuntu.yml
#   when: ansible_distribution == 'Ubuntu'

- name: set dotfiles
  git: repo='https://github.com/pogin503/dot-files.git'
       dest={{ ansible_env.HOME }}/dotfiles
       version=master
       force=yes

- name: exec setup.sh
  shell: "{{ ansible_env.HOME }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles/"
  register: ret
  changed_when: ret.rc != 0

- name: create iterm2 log directory
  become: true
  file: path=/var/log/iterm2 state=directory owner=root group=admin mode=0775
  when: ansible_os_family == 'Darwin'
