---
- name: install dpendencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - python3-pip
    - build-essential
    # mysql dependencies
    - libmysqlclient-dev
    - python3-dev
    - python3-pip
    - python3-mysqldb
    # ats2 dependency
    - libgmp3-dev
