---
- name: install dpendencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
    - { name: git }
    - { name: python3-pip }
    - { name: build-essential }
