---
- name: install dpendencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
    - { name: git }
    - { name: python3-pip }
    - { name: build-essential }
    # mysql dependencies
    - { name: libmysqlclient-dev }
    - { name: python3-dev }
    - { name: python3-pip }
    - { name: python3-mysqldb }
    # ats2 dependency
    - { name: libgmp3-dev }
