---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: macOS.yml
  when: ansible_os_family == 'Darwin'

# - name: install rbenv
#   git:
#     repo: https://github.com/sstephenson/rbenv.git
#     dest: "{{ my_rbenv_root }}"
#     version: master
#   when: ansible_distribution == 'Ubuntu'

- name: add rbenv path to bash_profile
  become: true
  template:
    src: templates/rbenv_user.sh.j2
    dest: /etc/profile.d/rbenv_user.sh
  when: not ansible_os_family == 'Darwin'

- name: install ruby_build
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest={{ my_rbenv_root }}/plugins/ruby-build
       version=master
  when: not ansible_os_family == 'Darwin'

- name: set rbenv setting
  shell: $SHELL -lc "export RBENV_ROOT={{ my_rbenv_root }}; export PATH=$RBENV_ROOT/bin:$PATH"
  args:
    creates: "{{ my_rbenv_root }}/versions/{{ my_ruby_version }}"
  changed_when: false
  check_mode: no

- name: install ruby
  shell: |
    echo N | rbenv install {{ my_ruby_version }} --skip-existing {{ my_ruby_version }}
    rbenv global {{ my_ruby_version }}
  args:
    creates: "{{ my_rbenv_root }}/versions/{{ my_ruby_version }}"

- name: set ruby {{ my_ruby_version }} for system
  command: $SHELL -lc "rbenv rehash"
  changed_when: false

# - name: check ruby installed version
#   shell: bash -lc "rbenv versions"
#   register: ruby_installed_version

# - name: change ~ owner to vagrant
#   file: path={{ my_rbenv_root }} state=directory owner=ubuntu group=vagrant recurse=yes


- name: install iruby dpendencies (macOS)
  block:
    - name: install iruby dependencies
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { name: zeromq, state: present }
        - { name: czmq, state: head }
    - name: iruby dependency
      gem:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        # Install ~/.rbenv/
        user_install: False
        executable: "{{ my_rbenv_root }}/shims/gem"
      with_items:
        - { name: cztop, state: present }
        - { name: iruby, state: present }
  when: ansible_os_family == 'Darwin'
