---
rbenv:
  env: user
  # version: v1.0.0
  default_ruby: 2.5.1
  rubies:
    - version: 2.5.1

my_ruby_version: 2.5.1
my_ruby_packages:
  # A toolkit of support libraries and Ruby core extensions extracted
  # from the Rails framework. Rich support for multibyte strings,
  # internationalization, time zones, and testing.
  - activesupport
  - bundler
  - pry

my_rbenv_root: "{% if rbenv.env == 'system' %}/usr/local/rbenv{% else %}~/.rbenv{% endif %}"
